// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "projectId": "test-project-id",
  "appId": "1:1011351605710:web:30e1de9b250e21d25edb9f",
  "storageBucket": "test-project-id.appspot.com",
  "apiKey": "AIzaSyDqGBvYbqI8-PG_qvEZBTq05fyMk3oyO7c",
  "authDomain": "test-project-id.firebaseapp.com",
  "messagingSenderId": "1011351605710"
};
